force-app/main/default/objects/PCQS_Service_Item__c/PCQS_Service_Item__c.object-meta.xml
<CustomObject>
    <label>PCQS Service_Item</label>
    <nameField>
        <displayFormat>PCQS-{0000000}</displayFormat>
        <label>PCQS Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PCQS Service Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PCQS_Service_Item__c/fields/A_Number__c.field-meta.xml
<CustomField>
    <fullName>A_Number__c</fullName>
    <label>A Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Origin__c</fullName>
    <label>Country of Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/Plaintiff_Gender__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_Gender__c</fullName>
    <label>Plaintiff Gender</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/Plaintiff_Port_of_Entry__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_Port_of_Entry__c</fullName>
    <label>Plaintiff Port of Entry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PcqsServiceAPI.cls
@RestResource(urlMapping='/pcqsAPI/*')
global with sharing class PcqsServiceAPI {
    @HttpGet
    global static List<PCQS_Service_Item__c> getServiceItems() {
        System.debug('Running PcqsServiceAPI.getServiceItems');
        RestRequest request = RestContext.request;
        String firstName = '';
        String lastName = '';
        String birthDateStr = '';
        String query = 'SELECT First_Name__c, Last_Name__c, A_Number__c, Birthdate__c, Country_of_Origin__c, Plaintiff_Gender__c, Plaintiff_Port_of_Entry__c FROM PCQS_Service_Item__c';
        Date birthDate = Date.today();

        if(request.params.containsKey('firstName') || request.params.containsKey('lastName') || request.params.containsKey('birthDate')){
            query = query + ' WHERE ';
        }

        if(request.params.containsKey('firstName')){
            query = query + ' First_Name__c = \'' + request.params.get('firstName') + '\'';
        }

        if(request.params.containsKey('firstName') && request.params.containsKey('lastName')){
            query = query + ' AND ';
        }

        if(request.params.containsKey('lastName')){
            query = query + ' First_Name__c = \'' + request.params.get('firstName') + '\'';
        }

        if((request.params.containsKey('firstName') || request.params.containsKey('lastName')) && request.params.containsKey('lastName')){
            query = query + ' AND ';
        }

        if(request.params.containsKey('birthDate')){
            birthDateStr = request.params.get('birthDate');
            birthDate = Date.valueOf(birthDateStr);
            query = query + ' Birthdate__c = ' + birthDateStr;
        }

        query = query + ' LIMIT 20';

        System.debug('Running the following Query: ' + query);

        List<PCQS_Service_Item__c> pcqsList = Database.query(query);

        return pcqsList;
    }
}