force-app/main/default/objects/PCQS_Service_Item__c/PCQS_Service_Item__c.object-meta.xml
<CustomObject>
    <label>PCQS Service_Item</label>
    <nameField>
        <displayFormat>PCQS-{0000000}</displayFormat>
        <label>PCQS Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PCQS Service Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PCQS_Service_Item__c/fields/A_Number__c.field-meta.xml
<CustomField>
    <fullName>A_Number__c</fullName>
    <label>A Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Origin__c</fullName>
    <label>Country of Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/Plaintiff_Gender__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_Gender__c</fullName>
    <label>Plaintiff Gender</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PCQS_Service_Item__c/fields/Plaintiff_Port_of_Entry__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_Port_of_Entry__c</fullName>
    <label>Plaintiff Port of Entry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PcqsServiceAPITest.cls
@IsTest
public class PcqsServiceAPITest {
    @TestSetup
    static void makeData(){
        PCQS_Service_Item__c pcqsTest = new PCQS_Service_Item__c(
            First_Name__c = 'Janessa',
            Last_Name__c = 'MacKegg',
            A_Number__c = '280500221',
            Birthdate__c = date.valueOf('1982-03-15'),
            Country_of_Origin__c = 'Syria',
            Plaintiff_Gender__c = 'Female',
            Plaintiff_Port_of_Entry__c = 'Calexico East - Class A, California - 2507'
        );

        insert pcqsTest;
    }

    @IsTest
    static void testGetServiceItems() {
        PCQS_Service_Item__c pcqsItem = [ SELECT First_Name__c, Last_Name__c, Birthdate__c FROM PCQS_Service_Item__c LIMIT 1];

        RestRequest  request    = new RestRequest();
        RestResponse response   = new RestResponse();

        request.requestURI = Url.getOrgDomainUrl().toExternalForm() + '/services/apexrest/pcqsAPI';
        request.httpMethod = 'GET';
        request.params.put('firstName', 'Janessa');
        request.params.put('lastName', 'MacKegg');
        request.params.put('birthDate', '1982-03-15');

        RestContext.request = request;
        RestContext.response = response;

        List<PCQS_Service_Item__c> resultsList = PcqsServiceAPI.getServiceItems();
        system.assert(resultsList.isEmpty() == false);
        system.assert(resultsList[0].First_Name__c == 'Janessa');
    }
}