force-app/main/default/objects/service_item__c/service_item__c.object-meta.xml
<CustomObject>
    <label>Service Item</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Service Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/service_item__c/fields/Attorney_Company__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Company__c</fullName>
    <label>Attorney Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/service_item__c/fields/Attorney_Email__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Email__c</fullName>
    <label>Attorney Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/service_item__c/fields/Attorney_Name__c.field-meta.xml
<CustomField>
    <fullName>Attorney_Name__c</fullName>
    <label>Attorney Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/service_item__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/service_item__c/fields/Plaintiff_A_Number__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_A_Number__c</fullName>
    <label>Plaintiff A Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/service_item__c/fields/Plaintiff_Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_Birthdate__c</fullName>
    <label>Plaintiff Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/service_item__c/fields/Plaintiff_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_First_Name__c</fullName>
    <label>Plaintiff First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/service_item__c/fields/Plaintiff_Gender__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_Gender__c</fullName>
    <label>Plaintiff Gender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/service_item__c/fields/Plaintiff_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_Last_Name__c</fullName>
    <label>Plaintiff Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/service_item__c/fields/Plaintiff_Port_of_Entry__c.field-meta.xml
<CustomField>
    <fullName>Plaintiff_Port_of_Entry__c</fullName>
    <label>Plaintiff Port of Entry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/service_item__c/fields/Plantiff_Country_Of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Plantiff_Country_Of_Origin__c</fullName>
    <label>Plaintiff Country of Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LWCOutlookController.cls
public with sharing class LWCOutlookController {

    @AuraEnabled
    public static List<Service_Item__c> ServiceItemLookup(string emailAddress){ 
       return [SELECT Attorney_Company__c, 
                      Attorney_Email__c, 
                      Attorney_Name__c, 
                      Plaintiff_A_Number__c, 
                      Plaintiff_Birthdate__c, 
                      Plantiff_Country_Of_Origin__c, 
                      Plaintiff_First_Name__c, 
                      Plaintiff_Gender__c, 
                      Plaintiff_Last_Name__c, 
                      Plaintiff_Port_of_Entry__c, 
                      Case_Number__c 
                 FROM Service_Item__c 
                WHERE Attorney_Email__c = :emailAddress];
    }

}